### PR TITLE
[DO NOT MERGE YET] Remove "bc-" prefix of barclamp id's

### PR DESCRIPTION
**Pull request by vwallfahrer**

### CODE REVIEW

**Comment by tboerger** [comment]
Do we need some kind of migrations for already existing installations? Otherwise :+1:

**Comment by rsalevsky** [comment]
@tboerger I don't think so, the only case when we can need one is the upgrade between 5 and 6.

+1

**Comment by tboerger** [comment]
So everybody needs to reset his development environment after merging this.

**Comment by vuntz** [comment]
+1, but waiting for M5 to be released before merging.

**Pull request merged**
